services:
  - type: web
    name: rayfoodpos
    env: php
    plan: starter
    buildCommand: composer install --optimize-autoloader --no-dev && npm ci && npm run build && php artisan storage:link
    startCommand: php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: rayfoodpos-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: rayfoodpos-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: rayfoodpos-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: rayfoodpos-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: rayfoodpos-db
          property: password
      - key: VITE_HOST
        sync: false
      - key: VITE_API_KEY
        sync: false

databases:
  - name: rayfoodpos-db
    plan: starter
    databaseName: rayfoodpos
    user: rayfoodpos_user

